services:
    postgres:
        image: postgres:17
        environment:
            POSTGRES_DB: ${DB_NAME:-leetcode_fake}
            POSTGRES_USER: ${DB_USERNAME:-postgres}
            POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
        ports:
            - "5432:5432"
    redis:
        image: redis:latest
        ports:
            - "6379:6379"
    